# toolchains/rust.bzl
#
# Hermetic Rust toolchain using Nix store paths.
#
# Paths are read from .buckconfig.local [rust] section, generated by `nix develop`.
# No PATH lookup. Just absolute Nix store paths.

load("@prelude//rust:rust_toolchain.bzl", "PanicRuntime", "RustToolchainInfo")

def _rust_toolchain_impl(ctx: AnalysisContext) -> list[Provider]:
    """
    Rust toolchain with paths from .buckconfig.local.

    Reads [rust] section for absolute Nix store paths:
      rustc       - Rust compiler
      rustdoc     - Documentation generator
      clippy      - Linter
      cargo       - Package manager (for build scripts)
    """

    # Read tool paths from config
    rustc = read_root_config("rust", "rustc", "rustc")
    rustdoc = read_root_config("rust", "rustdoc", "rustdoc")
    clippy_driver = read_root_config("rust", "clippy_driver", "clippy-driver")

    # Target triple
    target_triple = read_root_config("rust", "target_triple", "x86_64-unknown-linux-gnu")

    return [
        DefaultInfo(),
        RustToolchainInfo(
            compiler = RunInfo(args = [rustc]),
            rustdoc = RunInfo(args = [rustdoc]),
            clippy_driver = RunInfo(args = [clippy_driver]),
            rustc_target_triple = target_triple,
            default_edition = ctx.attrs.default_edition,
            panic_runtime = PanicRuntime(ctx.attrs.panic_runtime),
            rustc_flags = ctx.attrs.rustc_flags,
            rustc_binary_flags = ctx.attrs.rustc_binary_flags,
            rustc_test_flags = ctx.attrs.rustc_test_flags,
            rustdoc_flags = ctx.attrs.rustdoc_flags,
            allow_lints = ctx.attrs.allow_lints,
            deny_lints = ctx.attrs.deny_lints,
            warn_lints = ctx.attrs.warn_lints,
            report_unused_deps = ctx.attrs.report_unused_deps,
            doctests = ctx.attrs.doctests,
        ),
    ]

rust_toolchain = rule(
    impl = _rust_toolchain_impl,
    attrs = {
        "default_edition": attrs.string(default = "2021"),
        "panic_runtime": attrs.string(default = "unwind"),
        "rustc_flags": attrs.list(attrs.string(), default = []),
        "rustc_binary_flags": attrs.list(attrs.string(), default = []),
        "rustc_test_flags": attrs.list(attrs.string(), default = []),
        "rustdoc_flags": attrs.list(attrs.string(), default = []),
        "allow_lints": attrs.list(attrs.string(), default = []),
        "deny_lints": attrs.list(attrs.string(), default = []),
        "warn_lints": attrs.list(attrs.string(), default = []),
        "report_unused_deps": attrs.bool(default = False),
        "doctests": attrs.bool(default = False),
    },
    is_toolchain_rule = True,
)
