{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Aleph.Script.Vm.Config
Description : VM configuration types from Dhall

Type-safe configuration for Firecracker and Cloud Hypervisor VMs.
These types correspond to the Dhall schemas in Weyl/Config/ and
are populated by Nix at build time.

@
-- Read config from file generated by Nix:
cfg <- loadConfigFile @FirecrackerConfig "/nix/store/xxx/config.dhall"

-- Use type-safe paths:
let kernel = fcKernelPath cfg  -- StorePath, not String!
@
-}
module Aleph.Script.Vm.Config (
    -- * Firecracker
    FirecrackerConfig (..),
    loadFirecrackerConfig,

    -- * Cloud Hypervisor
    CloudHypervisorConfig (..),
    loadCloudHypervisorConfig,
) where

import Data.Text (Text)
import Dhall (FromDhall (..), auto, inputFile)
import GHC.Generics (Generic)
import Numeric.Natural (Natural)

import Aleph.Script.Config (StorePath (..), storePathToFilePath)

-- ============================================================================
-- Firecracker
-- ============================================================================

{- | Firecracker runtime configuration

Populated by Nix with real store paths. The field names must match
the Dhall record fields exactly.
-}
data FirecrackerConfig = FirecrackerConfig
    { kernel :: StorePath
    -- ^ vmlinux kernel path
    , busybox :: StorePath
    -- ^ busybox binary for init
    , initScript :: StorePath
    -- ^ init script for interactive run
    , buildInitScript :: StorePath
    -- ^ init script for build mode (runs command and exits)
    , defaultCpus :: Natural
    -- ^ default vCPU count
    , defaultMemMib :: Natural
    -- ^ default memory in MiB
    , cacheDir :: Text
    -- ^ OCI image cache directory
    }
    deriving stock (Show, Generic)

instance FromDhall FirecrackerConfig

-- | Load Firecracker config from Dhall file
loadFirecrackerConfig :: FilePath -> IO FirecrackerConfig
loadFirecrackerConfig = inputFile auto

-- ============================================================================
-- Cloud Hypervisor
-- ============================================================================

-- | Cloud Hypervisor runtime configuration
data CloudHypervisorConfig = CloudHypervisorConfig
    { chKernel :: StorePath
    -- ^ vmlinux kernel path
    , chBusybox :: StorePath
    -- ^ busybox binary for init
    , chInitScript :: StorePath
    -- ^ init script to inject into rootfs
    , chGpuInitScript :: Maybe StorePath
    -- ^ GPU-specific init script (optional)
    , chDefaultCpus :: Natural
    -- ^ default vCPU count
    , chDefaultMemMib :: Natural
    -- ^ default memory in MiB
    , chHugepages :: Bool
    -- ^ use hugepages for memory
    , chCacheDir :: Text
    -- ^ OCI image cache directory
    }
    deriving stock (Show, Generic)

instance FromDhall CloudHypervisorConfig

-- | Load Cloud Hypervisor config from Dhall file
loadCloudHypervisorConfig :: FilePath -> IO CloudHypervisorConfig
loadCloudHypervisorConfig = inputFile auto
