# Root BUCK file
#
# Build targets:
#   buck2 build //src:hello
#   buck2 build //src:nv_hello (requires NVIDIA)
#
# Run:
#   buck2 run //src:hello

load("@prelude//utils:source_listing.bzl", "source_listing")

source_listing()
